### ISSUE TITLE
Error Handling for Server Call 

### ISSUE THREAD

**Issue by SoniaAnn** [TempleOfArtemis/FEC_main#93]
Hey @benjaminlthornton. Great work separating your concerns by keeping server calls in a separate file!

## Description
I noticed that you are missing error handling for your metaData call. Just like you do on your other server functions, it's important to add error handling to this call.

## Tasks/Suggestions

- [x] Add a .catch block that includes error handling 
- [x] Similar to your other calls it might be useful to have a descriptive console message with the error that relates to the function that erred. 

## Files
https://github.com/TempleOfArtemis/FEC_main/blob/67594d27c07f8b71da1971274616fd34cd304bee/client/src/Ratings-Reviews/RRcomponents/ReviewList/serverAction.jsx#L17-L19

**Comment by benjaminlthornton** [comment]
Ended up not using that function after we refactored to make the meta call at the top. Deleted the function.
